name: "bluebell"
mode: "dev"
port: 8080
version: "v0.0.1"
start_time: "2025-05-10"
machine_id: 1



log:
  level: "debug"
  filename: "web_app2.log"
  maxsize: 200
  maxage: 30
  maxbackups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  pwd: "zgw64220392"
  dbname: "go"
  max_open: 100
  max_idle: 100

redis:
  host: "127.0.0.1"
  port: 6379
  pwd: ""
  pool_size: 100
  db: 0

