app:
  name: "web_app"
  mode: "dev"
  port: 8081

log:
  level: "debug"
  filename: "web_app.log"
  maxsize: 200
  maxage: 30
  maxbackups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  pwd: "64220392"
  dbname: "go"
  max_open: 100
  max_idle: 100

redis:
  host: "127.0.0.1"
  port: 6379
  pwd: ""
  pool_size: 100
  db: 0

